name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/build-docker.yaml"
      - ".vscode/**"
      - "docs/**"
      - "**.md"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ten-framework/ten_agent_build:0.4.10
    strategy:
      matrix:
        agent: [agents/examples/default, agents/examples/demo]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - name: Use agent
        run: |
          task use AGENT=${{ matrix.agent }}

      - name: Run tests
        run: |
          task test -- -s -v

